print('Your code language sucks')
print('You need Casting')
print('Made by Python Gang')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')

print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
print('Python codeeee')
